version: '2.0'
services:
  sniffer:
    container_name: sniffer-rails
    env_file: 
      - .env
    depends_on: 
      - db
      - redis
    command: sh scripts/start.sh
    image: mzsrn/sniffer:env
    ports:
      - "3000:3000"
    links:
      - redis
  sidekiq:
    env_file: 
      - .env
    depends_on: 
      - db
      - redis
    command: sh scripts/start_sidekiq.sh
    image: mzsrn/sniffer:env
    container_name: sniffer-sidekiq
    links:
      - redis
  redis:
    image: redis
    container_name: sniffer-redis
  db:
    container_name: sniffer-postgres
    image: postgres:9.6
    environment: 
      - POSTGRES_PASSWORD=123123