development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] || 'redis://localhost' %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] || 'redis://localhost' %>
  channel_prefix: rnds_web_sniffer_production
